"""HTML report generation for scAgent-DPM."""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger("scagent_dpm.reporting.html")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>scAgent-DPM Pipeline Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 960px; margin: 40px auto; padding: 0 20px; line-height: 1.6;
         color: #333; background: #fafafa; }}
  h1 {{ border-bottom: 2px solid #2563eb; padding-bottom: 8px; }}
  h2 {{ color: #1e40af; margin-top: 32px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background: #f0f4ff; }}
  .warning {{ background: #fff3cd; border-left: 4px solid #f59e0b; padding: 12px 16px; margin: 16px 0; }}
  .error {{ background: #fee2e2; border-left: 4px solid #ef4444; padding: 12px 16px; margin: 16px 0; }}
  .success {{ background: #dcfce7; border-left: 4px solid #22c55e; padding: 12px 16px; margin: 16px 0; }}
  .footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 0.85em; color: #666; }}
</style>
</head>
<body>
{content}
</body>
</html>"""


def generate_html_report(results: Dict[str, Any], output_dir: str) -> Path:
    """Generate an HTML report from pipeline results."""
    sections = []

    sections.append(f"<h1>scAgent-DPM Pipeline Report</h1>")
    sections.append(f"<p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>")

    # System status
    sections.append("<h2>System Status</h2>")
    anno = results.get("annotation", {})
    dyn = results.get("dynamics", {})

    has_fallback = False
    if isinstance(anno, dict) and anno.get("is_fallback"):
        has_fallback = True
    if isinstance(dyn, dict) and dyn.get("is_fallback"):
        has_fallback = True

    if has_fallback:
        sections.append(
            '<div class="warning"><strong>WARNING:</strong> This report contains FALLBACK/MOCK results. '
            'These results are for interface testing only and MUST NOT be used for publication.</div>'
        )
    else:
        sections.append('<div class="success">Pipeline completed successfully.</div>')

    # DPRS Table
    dprs_df = results.get("dprs_df")
    if dprs_df is not None and hasattr(dprs_df, "to_html"):
        sections.append("<h2>Drug Perturbation Response Scores (DPRS)</h2>")
        try:
            html_table = dprs_df.head(20).to_html(index=False, classes="dprs-table",
                                                    float_format="%.4f")
            sections.append(html_table)
        except Exception:
            sections.append("<p>DPRS table could not be rendered.</p>")

    # Available and missing components
    dprs_meta = results.get("dprs_meta", {})
    if dprs_meta:
        available = dprs_meta.get("available_components", [])
        missing = dprs_meta.get("missing_components", [])
        sections.append("<h2>Components</h2>")
        sections.append(f"<p><strong>Available:</strong> {', '.join(available) if available else 'None'}</p>")
        sections.append(f"<p><strong>Missing:</strong> {', '.join(missing) if missing else 'None'}</p>")

    # Output files
    sections.append("<h2>Output Files</h2>")
    sections.append("""<table>
<tr><th>File</th><th>Description</th></tr>
<tr><td>data_summary.json</td><td>Data inspection report</td></tr>
<tr><td>qc_report.json</td><td>Quality control report</td></tr>
<tr><td>cell_annotation.csv</td><td>Cell type predictions</td></tr>
<tr><td>dprs_scores.csv</td><td>DPRS per cell type</td></tr>
<tr><td>drug_sensitive_cell_types.csv</td><td>Drug-sensitive populations</td></tr>
<tr><td>perturbation_summary.json</td><td>Perturbation analysis summary</td></tr>
<tr><td>run_manifest.json</td><td>Full execution manifest</td></tr>
<tr><td>execution_graph.json</td><td>Execution DAG</td></tr>
</table>""")

    sections.append('<div class="footer">Generated by scAgent-DPM v0.1.0</div>')

    html_content = HTML_TEMPLATE.format(content="\n".join(sections))
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / "report.html"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    logger.info(f"HTML report saved to {report_path}")
    return report_path
